AllCops:
  Exclude:
    - "acceptance/**/*"
    - "integration/**/*"
    - "opencensus.gemspec"
    - "Rakefile"
    - "support/**/*"
    - "test/**/*"
    - "docs/**/*"
    - "tmp/**/*"

Documentation:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Metrics/AbcSize:
  Max: 25
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 20
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 10
Style/CaseEquality:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/NumericLiterals:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrivialAccessors:
  Enabled: false
