version: 2
jobs:
  Test Ruby 2.2:
    docker:
      - image: circleci/ruby:2.2-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Bundle
          command: gem install --no-document bundler:1.17.3 && bundle install
      - run:
          name: CI on Ruby 2.2
          command: bundle exec rake
  Test Ruby 2.3:
    docker:
      - image: circleci/ruby:2.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Bundle
          command: gem install --no-document bundler:1.17.3 && bundle install
      - run:
          name: CI on Ruby 2.3
          command: bundle exec rake
  Test Ruby 2.4:
    docker:
      - image: circleci/ruby:2.4-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Bundle
          command: gem install --no-document bundler:1.17.3 && bundle install
      - run:
          name: CI on Ruby 2.4
          command: bundle exec rake
  Test Ruby 2.5:
    docker:
      - image: circleci/ruby:2.5-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Bundle
          command: gem install --no-document bundler:1.17.3 && bundle install
      - run:
          name: CI on Ruby 2.5
          command: bundle exec rake
  Test Ruby 2.6:
    docker:
      - image: circleci/ruby:2.6-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Bundle
          command: gem install --no-document bundler:1.17.3 && bundle install
      - run:
          name: CI on Ruby 2.6
          command: bundle exec rake
workflows:
  version: 2
  tests:
    jobs:
      - Test Ruby 2.2
      - Test Ruby 2.3
      - Test Ruby 2.4
      - Test Ruby 2.5
      - Test Ruby 2.6
